# Generated by Django 4.2.16 on 2025-12-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('params', models.JSONField(default=dict)),
                ('progress_done', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=0)),
                ('last_message', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('n', models.IntegerField()),
                ('k', models.IntegerField(blank=True, null=True)),
                ('degrees', models.JSONField()),
                ('degrees_hash', models.CharField(db_index=True, max_length=64)),
                ('algorithm', models.CharField(max_length=32)),
                ('edges', models.JSONField()),
                ('graph6_b64', models.TextField()),
                ('canonical_g6_b64', models.TextField()),
                ('graph6_decoded', models.TextField(blank=True, null=True)),
                ('canonical_g6_decoded', models.TextField(blank=True, null=True)),
                ('time_ms', models.IntegerField()),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('is_graphical', models.BooleanField(default=True)),
                ('objective_name', models.CharField(default='spectral_radius', max_length=64)),
                ('objective_mode', models.CharField(default='min', max_length=3)),
                ('objective_value', models.FloatField(blank=True, null=True)),
                ('spectral_radius', models.FloatField(blank=True, null=True)),
                ('iterations', models.IntegerField(blank=True, null=True)),
                ('accepted_moves', models.IntegerField(blank=True, null=True)),
                ('meta_params', models.JSONField(blank=True, null=True)),
                ('triangles', models.IntegerField(blank=True, null=True)),
                ('avg_path_len', models.FloatField(blank=True, null=True)),
                ('clustering', models.FloatField(blank=True, null=True)),
                ('is_connected', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degrees_hash', models.CharField(db_index=True, max_length=64)),
                ('mode', models.CharField(max_length=3)),
                ('objective_name', models.CharField(default='spectral_radius', max_length=64)),
                ('prev_best_value', models.FloatField(blank=True, null=True)),
                ('new_best_value', models.FloatField()),
                ('improvement', models.FloatField(blank=True, null=True)),
                ('anomaly_flags', models.JSONField(default=list)),
                ('note', models.TextField(blank=True, default='')),
                ('best_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='core.run')),
            ],
            options={
                'indexes': [models.Index(fields=['degrees_hash', 'mode'], name='core_discov_degrees_b548b0_idx')],
            },
        ),
    ]
