# Generated by Django 4.2.16 on 2025-12-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='connected_only',
            field=models.BooleanField(default=False),
        ),
    ]
